### ISSUE TITLE
Email subject too long

### ISSUE THREAD

**Issue by lzappaterra** [filebot/scripts#14]
![2015-04-21 11_27_33-gmail - filebot 1992 1x01 episodio 1 ita hdtvrip x264-novarip 1992 1x02 episo](https://cloud.githubusercontent.com/assets/12046413/7249306/b9b8596a-e819-11e4-9a9c-af21f836a4e4.png)
When you use amc script to process multiple files the subject of the email report contains the name of all the processed files (see attachments). This add wheight to the reading of the email, and maybe it could be simpler, for example deleting the entire getNotificationMessage from the email subject.
It's just a suggestion.

Above the two lines involved.
def getReportSubject = { getNotificationMessage('', ', ') }
def getReportTitle = { '[FileBot] ' + getReportSubject() }

**Comment by rednoah** [comment]
Set --def ut_title (as per all examples) to change the report subject to something more meaningful.
