### ISSUE TITLE
AMC Ignore List For Cleanner script

### ISSUE THREAD

**Issue by LePastis** [filebot/scripts#17]
Ignore list should be give to the cleanner script to prevent deletion of file unaffected by the process.

**Comment by rednoah** [comment]
There's --def ignore=regex and you can seen what it does if you look at the first view lines of the cleaner script.

**Comment by LePastis** [comment]
I'm sorry if I was not clear. I know the cleanner script takes as argument - def ignore = regex like the AMC script.

By cons, if one defines ignore=something and clean = y for the AMC script, the ignore parameter is not transferred to cleanner script. What makes cleanner script delete files that should have been ignored.

**Comment by rednoah** [comment]
I see.

**Comment by rednoah** [comment]
Fixed. Please test and confirm it's working.

@see https://github.com/filebot/scripts/commit/d67e26af8e873e6ecaf0ab49da0b3c024cf502ed
