### ISSUE TITLE
Gmail option doesnt work anymore

### ISSUE THREAD

**Issue by kevmegforest** [filebot/scripts#19]
In amc scripts, I can not send anymore email via gmail option because of new authentification at gmail server.

Please fix

**Comment by rednoah** [comment]
So you're saying Gmail no longer supports SMTP? What changed?

**Comment by rednoah** [comment]
Fixed, possibly:
https://github.com/filebot/scripts/commit/895f3fcca02b447ad8da30e5d85cd3c9a3bcf1e4

Haven't tested it yet.

Forums: https://www.filebot.net/forums/viewtopic.php?f=6&t=3146
