### ISSUE TITLE
FileBot adding extra path when using scipt "renall"

### ISSUE THREAD

**Issue by jcouch93** [filebot/scripts#23]
FileBot 4.6.1 (r3315) / Java(TM) SE Runtime Environment 1.8.0_71 on WHS2011

When I run the following script:
`C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia>filebot -script fn:renall "D:/Videos/JC/_NEW_/Movies" -non-strict --db TheMovieDB --output "D:/Videos/JC/Movies" --format "{n} ({y}) ({vf})/{n} ({y}) ({vf})"`

I see this in the command window:
```
C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia>"Filebot - JC - Movies.bat"

C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia>REM @ECHO OFF

C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia>filebot -script fn:renall "D:/Videos/
JC/_NEW_/Movies" -non-strict --db TheMovieDB --output "D:/Videos/JC/Movies" --format "{n} ({y}) ({vf
})/{n} ({y}) ({vf})" --action test  . 1>"D:/Videos/JC/_NEW_/filebot-movies.log"
```

I see this in the log:
**Rename movies using [TheMovieDB]
Auto-detect movie from context: [C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia\tests\test.mp4]
[TEST] Rename [C:\Program Files (x86)\SABnzbd\Post-Process_Scripts\nzbToMedia\tests\test.mp4] to [D:\Videos\JC\Movies\Abduction (2009) (576p)\Abduction (2009) (576p).mp4]
Processed 1 files**
Rename movies using [TheMovieDB]
Auto-detect movie from context: [D:\Videos\JC\_NEW_\Movies\Crimson.Peak.2015.1080p.BluRay.x264.DTS-JYK-Obfuscated\Mbpew44sQytpMppGyt0FS8yKWsyqrVzDenhSBwYNd4kVXy9kvxkDx.mkv]
[TEST] Rename [D:\Videos\JC\_NEW_\Movies\Crimson.Peak.2015.1080p.BluRay.x264.DTS-JYK-Obfuscated\Mbpew44sQytpMppGyt0FS8yKWsyqrVzDenhSBwYNd4kVXy9kvxkDx.mkv] to [D:\Videos\JC\Movies\Crimson Peak (2015) (1080p)\Crimson Peak (2015) (1080p).mkv]
Processed 1 files
Rename movies using [TheMovieDB]
Auto-detect movie from context: [D:\Videos\JC\_NEW_\Movies\The.Last.Witch.Hunter.2015.1080p.BluRay.AC3.x264-ETRG-Obfuscated\ub1u9XcG37FJc.mkv]
[TEST] Rename [D:\Videos\JC\_NEW_\Movies\The.Last.Witch.Hunter.2015.1080p.BluRay.AC3.x264-ETRG-Obfuscated\ub1u9XcG37FJc.mkv] to [D:\Videos\JC\Movies\The Last Witch Hunter (2015) (1080p)\The Last Witch Hunter (2015) (1080p).mkv]
Processed 1 files
Done ?(?????)?

The bolded section is the one I can't get to work correctly.  In the script I am specifying the directory that all my new movies are in but FB seems to always want to include the dir that it's in.  I wouldn't think that would be desired if I am setting that in the script itself?  I have the script in that dir because SABnzbd expects it there and I have other scripts already there.  Is there a way to make FB only look in the dir I specify?  Thanks!

**Comment by rednoah** [comment]
1.
> When I run the following script...

No you're not... The output clearly shows you calling a batch file `Filebot - JC - Movies.bat`. You're certainly not calling the command you say you're calling.

2.
`.` means *current directory* just like `..` means parent directory. You're passing in 2 arguments, one specific folder, and the current directory. I recommend learning some CMD basics.

**Comment by jcouch93** [comment]
Thank you for #2, I believe that was what was causing the issue.
