### ISSUE TITLE
The Originals AMC sort behavior.

### ISSUE THREAD

**Issue by mels0n** [filebot/scripts#24]
Not sure why it sorted incorrectly. But, here is the log.

Run script [fn:amc] at [Sat Feb 13 02:02:31 CST 2016]
Parameter: excludeList = t:/amc.txt
Parameter: ut_label = Series
Parameter: clean = y
Argument: T:\BT Sync\TV Shows
Using excludes: t:\amc.txt (84)
Input: T:\BT Sync\TV Shows\The.Originals.S03E12.720p.HDTV.X264-DIMENSION.mkv
Group: [tvs:the originals] => [The.Originals.S03E12.720p.HDTV.X264-DIMENSION.mkv]
Rename episodes using [TheTVDB]
Auto-detected query: [The Originals]
Fetching episode data for [The Originals]
Error while loading XML resource: http://thetvdb.com/api/694FAD89942D3827/series/266883/all/en.xml (java.io.IOException: Malformed XML: http://thetvdb.com/api/694FAD89942D3827/series/266883/all/en.xml (XML document structures must start and end within the same entity.))
Fetching episode data for [SAS: The Originals]
Fetching episode data for [The Originals With Emeril]
[MOVE] Rename [T:\BT Sync\TV Shows\The.Originals.S03E12.720p.HDTV.X264-DIMENSION.mkv] to [t:\TV Shows\The Originals With Emeril\Season 01\The Originals With Emeril - S01E12 - New York City 2.mkv]
Processed 1 files
Clean clutter files and empty folders
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by rednoah** [comment]
This issue seems to have been caused by a temporary issue with TheTVDB. It should work now.
