### ISSUE TITLE
Update Sickbeard / Sickrage when Filebot finishes

### ISSUE THREAD

**Issue by vember31** [filebot/scripts#25]
I currently am using Sickrage (Sickbeard fork) to monitor and download torrents.  It's able to start the download, but has no way to monitor completion because I have post-processing turned off and instead use filebot (because it's absolutely amazing!!)

I'd like to have Sickrage re-scan the directory where the renamed files go once filebot has finished copying the file to the renamed directory. This will update the library.  To do this, Sickrage needs the tvdb ID of the show that was just downloaded and renamed by filebot.   I've been trying to figure out the best way to get the tvdb ID after the download completes, but am not sure of how to do so unfortunately.

Ideally, I'd be able to pass the tvdb ID that's gathered by filebot into this API after filebot is done: [http://sickbeard.com/api/#showrefresh](url)

Such that I call this URL after filebot in my Deluge script: http://[IP where I'm hosting Sickrage]:8081/api/[API key from Sickrage]/?cmd=show.refresh&tvdbid=[tvdb ID from filebot]

This would refresh the Sickrage library for whatever show is represented by the tvdb ID.

Do you have any suggestions for how I could go about this?  If it makes sense to incorporate into the amc groovy script to execute at the end (must be after file has finished copying since Sickrage tracks size of directory and that should be accurate), that would be awesome :) 

Appreciate your help and the hard work you've put in to make filebot so so good @rednoah. Apologies for such a long post!

**Comment by rednoah** [comment]
Interesting request! You can easily get the series ID via `xattr` from the file.

Come to think of it... if `xattr` is working, then this will work right out-of-the-box:
```
--def exec="echo 'http://localhost:8081/api/APIKEY?cmd=show.refresh&tvdbid={info.id}'"
```

**Comment by vember31** [comment]
Thanks!  This will complete my automation process for TV shows!!

In my shell script that's called by Deluge, I have the amc script being executed, followed now by:

`filebot -script fn:xattr --def exec="curl 'http://localhost:8081/api/APIKEY?cmd=show.refresh&tvdbid={info.id}'"`

I gave it a shot with a new torrent but no luck :/ for testing, I also called it straight from terminal and plugged in a defined value for a show I have instead of using {info.id} to see if it would work, but it did not.  I only see 'done' and your emoji after running it at the terminal.  I don't have any files being generated by xattr as I haven't used it before...does that matter here or is my command set up wrong?  I'm leaning towards the latter...

As a note, when I pasted that URL into the browser, it successfully updated in Sickrage.  In both the script and when I pasted into the browser, I was sure to add the API key in.

Appreciate your time :)

**Comment by rednoah** [comment]
`--def exec` is an option for the `amc` script. You do not need to use the `xattr` script.

**Comment by Panderine** [comment]
Also make sure to replace APIKEY with your actual api key.

**Comment by Maximillion195** [comment]
Hi rednoah,

I cant seem to get this to work;
--def exec="curl 'http://localhost:8081/api/APIKEY?cmd=show.refresh&tvdbid={info.id}'"

Is the {info.id} variable still valid? The only variable I can get to work is {folder}

Thanks!

**Comment by vember31** [comment]
First I'd like to apologize that I hadn't confirmed this was working.  It works great.  I'm using exactly the code from above (with a change to the IP and APIKEY).  So the info.id variable is working.  Of course make sure you have curl installed too.

`exec="curl 'http://localhost:8081/api/APIKEY?cmd=show.refresh&tvdbid={info.id}'"`

**Comment by Maximillion195** [comment]
Thanks for the reply vember, So you are using the latest amc script? and does your still work if you change the action to test?

I have this exact line in my code:
exec="curl 'http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}'"

And the output:
Execute: curl 'http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid='
{"data": {}, "message": "The required parameter: 'tvdbid' was not set", "result": "error"}

**Comment by Maximillion195** [comment]
Turns out this command gives the above error if you have the action set to test. When it is set to copy or move etc {info.id} works correctly.

**Comment by rednoah** [comment]
`{id}` should be giving you the series id. Use `--def exec="echo {json}"` to see the raw metadata as json.

**Comment by Knude** [comment]
I cannot seem to get this to work in Windows.
I am not a super experienced, but i thiink it is because of the quotes around it. 
When i use this one. in cmd with double quote instead of a single it does work..
Like this.
curl "http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}"
Instead of
curl 'http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}'

But when i try to but it together with AMC, i need to write it out like Maximillion did where there are single quotes on the link, otwerwise it won't go trhough.
exec="curl 'http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}'"

**Comment by rednoah** [comment]
`curl` is a Unix tool and won't work on Windows
`'...'` style quotes won't work on Windows

**Comment by Knude** [comment]
Yea i know. the commands line works fine, as i installed curl for windows.
as in it returns this.
`curl "http://localhost:8081/api/7887651aac8a9c08cf1463eb797a690e?cmd=show.refresh&tvdbid=322168"
{"data": {}, "message": "Grethe has queued to be refreshed", "result": "success"}`

but i am not able to use
`exec="curl 'http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}'"`
because of the different quotes.

**Comment by rednoah** [comment]
You just need to escape the argument value properly:
```
--def exec="curl \"http://localhost:8081/api/KEY?cmd=show.refresh&tvdbid={info.id}\""
```

**Comment by Knude** [comment]
So you can do it that way, nice to know :) Sadly it doesn't seem to fix the problem, might be because of the &, which might be understood wrong..
as in only this paremeter goes through
`Parameter: exec = curl "http://localhost:8081/api/KEY?cmd=show.refresh`

and ends up giving an error after the &
`'tvdbid' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by rednoah** [comment]
Well, a round of applause for CMD taking stupid to a whole new level.

Here's how it works:
http://stackoverflow.com/a/15262019/1514467

**Comment by rednoah** [comment]
FileBot will use `powershell -Command` instead of `cmd /c` starting with `r4757`.

**Comment by CurtC2** [comment]
When do you think r4757 will be available?

**Comment by rednoah** [comment]
Have you tried the latest release?
```
$ filebot -version
FileBot 4.7.8 (r4846)
```

**Comment by CurtC2** [comment]
Apologies, I was watching script commits rather than FileBot, my mistake.  Thanks!

**Comment by CurtC2** [comment]
Confirmed this command format works perfectly now in QBittorrent:

`exec="curl 'http://localhost:8081/api/YOURAPIKEY?cmd=show.refresh&tvdbid={info.id}'"`

Thank you!
