### ISSUE TITLE
Miss.Groovy cannot get property 'seriesInfo' on null object

### ISSUE THREAD

**Issue by barryanders** [filebot/scripts#26]
Was just trying to use fn:miss and kept running into this error every time I tried to use it. I noticed that the change to seriesInfo was a recent one in the commits and yet backing up that commit doesn't fix it either (since the previous commits before it were form 2014).

Anyway, I'm guessing it has something to do with me rather than the script, but I have run it in a folder where I know for a fact that I'm missing an episode.

This is the line that was run:
`filebot -script fn:miss .`

which led to the following error message.
 
```
NullPointerException: Cannot get property 'seriesInfo' on null object
java.lang.NullPointerException: Cannot get property 'seriesInfo' on null object
	at Script1$_run_closure1.doCall(Script1.groovy:9)
	at Script1.run(Script1.groovy:6)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:61)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:82)
	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:116)
	at net.filebot.Main.main(Main.java:169)
Failure (°_°)
```

I was wondering if this was returning due to some tagging error, however, I have renamed the files on a Mac using the FileBot App so I assume the files have been tagged properly.

When I run the script without specifying a directory, it runs correctly, since nothing is being processed and returns `Done ヾ(＠⌒ー⌒＠)ノ`.

**Comment by rednoah** [comment]
Have you tried `dev:miss` to make sure you're running the latest GitHub revision?

**Comment by rednoah** [comment]
There was a commit missing in the `m1` / `fn` branch. https://github.com/filebot/scripts/commit/fb07344c7116376a93efd068de9eaaa2872fd771

**Comment by barryanders** [comment]
Ah, yeah didn't realize that it was an alias for the script directly on Github, or that dev was an option apart from fn. I'll keep playing with it to give me the outcome I want. At least now I'm getting it to return files I already have. Just need to reverse it somehow.

**Comment by rednoah** [comment]
Output should look something like this:
```
$ filebot -script dev:miss .
TheTVDB::78874 | Firefly - 1x01 - The Train Job | Firefly - 1x01 - The Train Job.mkv
Firefly - 1x02 - Bushwhacked
Firefly - 1x03 - Our Mrs. Reynolds
...
```

First it'll log the metadata for each file, and then it'll print the missing episodes. You can turn off the former by adding `--log OFF`.

**Comment by barryanders** [comment]
I can confirm the previous concluded information as correct. Thankfully, once FileBot has renamed the files, it's super easy to rerename them and let FileBot do all the tagging :)

Thanks for your help @rednoah

**Comment by rednoah** [comment]
Let me know if you find any issue. This script was outdated and broken before you asked and I had another look to see if it still works. :D
