### ISSUE TITLE
Cleaner not working anymore

### ISSUE THREAD

**Issue by arckosfr** [filebot/scripts#32]
Hello,
Since i don't know, the cleaner don't detect anymore the left empty symlink.
When i launch the script, it just say Done, but nothing is done.
( i checked with `find / -type l | perl -lne 'print if ! -e'` and it show me some of error symlink)

**Comment by rednoah** [comment]
The cleaner script doesn't deal with symlinks one way or another. It probably doesn't even know what folder/file is a symlink. What is it supposed to be doing anyway?

**Comment by arckosfr** [comment]
Someone have lied to me...
Sorry for the useless issue then.
I close it

**Comment by rednoah** [comment]
I still don't know what you tried to do. Delete broken symlinks?

**Comment by arckosfr** [comment]
Yep its that, so by now i delete with sh script

**Comment by rednoah** [comment]
Yeah, you don't need the cleaner script for generic tasks like that.
