### ISSUE TITLE
amc script rename step optimization

### ISSUE THREAD

**Issue by queimadus** [filebot/scripts#36]
The default behaviour of the rename step is to use what was specified in the  `--action` argument.

But even if the user specified `copy` as that action, when temporary files are created (e.g. the target was a zip file instead of a singular video file), this can be optimized to a `move` if `clean`is enabled since it will be deleted afterwards anyhow.

This would avoid doing an unnecessary copy.

**Comment by rednoah** [comment]
If input/output are on different filesystems, you won't get around making a physical copy.
If input/output are on the same filesystem then you should be using `--action hardlink` anyway.

**Comment by queimadus** [comment]
I was unaware of `--action duplicate`. It completely mitigates the issue at hand.

Thanks 👍
