### ISSUE TITLE
fn:amc "pre-exec"

### ISSUE THREAD

**Issue by MoonshineSG** [filebot/scripts#43]
is there a way to run a pre-exec script? meaning running a command *before* the actual files are copied ? 
I tried to run the same script with "test" instead of "copy" as action but that, unfortunately, does not populate the "{n}",  "{s}" etc variables...

running on  filebot 4.7.2 on OSX, with TV shows.

**Comment by rednoah** [comment]
What's the use case?

**Comment by MoonshineSG** [comment]
i have 2 media storages. 
one main and one mobile (used when traveling). 
filebot does the update of the main storage and I'd like it to add any new shows to the mobile as well. 

1. Check if the folder where this episode belongs to has any files. (if the folder is empty, it means it's a brand new tv show) (count all files in the destination folder ignoring invisible ones : ` find SHOW_DESTINATION_FOLDER -type f \( ! -iname ".*" \) | wc -l` > 0)
2. step 2, run filebot amc as per usual, which will copy the episode to it's right place.  (this works almost perfectly for a while now)
3. if step one is "yes", copy the new episode to the mobile as well... 

I can't get SHOW_DESTINATION_FOLDER **before** copying, and obviously, after, is never gona be empty :D

**Comment by MoonshineSG** [comment]
This is just my first idea, and maybe there are other ways to do it...


But... shouldn't  the variables be populated even on "test" mode ?

**Comment by rednoah** [comment]
1.
Use amc script as usual to populate your main storage.

2.
Use `filebot -rename /primary/storage --action copy --db xattr --output /secondary/mirror --format {plex}` to mirror files to your secondary storage.

**Comment by rednoah** [comment]
Adding a filter such as `--filter "age < 30"` will allow you to mirror only episodes originally aired in the last 30 days.

You could also check the video codec and only mirror episodes where the video codec is compatible with your mobile device.

**Comment by MoonshineSG** [comment]
hmmm... none of the above suggested solutions doesnt really work for my case.

it might be a case where I add older shows. could be last year shows that I was not aware of ... for example

and for the mirror/copy, how can I know that this is a new show ? (note that the show folder might have been already there , empty, for a long time (added by Sickbeard for shows that I add way in advance)


yes, these are special cases, and the only common feature I can think of is the empty folder prior to running filebot. 
thats why running a "test" before the real "copy" to check the destination folder... but "test" does not set the show name, episode or season.. basically not much...

**Comment by MoonshineSG** [comment]
I found a ...strange solution...

I run the script with `seriesFormat="{n}"` then in "exec" I can read `{fn}` (which now is basically just `{n}`)...

Still strange that {fn} gets populated, while {n} does not  (in "exec")

**Comment by rednoah** [comment]
1.
`{fn}` is the filename. `{n}` is the movie/episode name.

2.
Why do you need to know what's a new show? Just do `filebot -rename -r /primary/storage --action copy --db xattr --output /secondary/mirror --format {plex}` and the whole folder.

**Comment by MoonshineSG** [comment]
1. I know. By setting `seriesFormat="{n}"` the 2 are identical :D It works, so I am happy that I found a workaround. 
"{n} is based on xattr data, but in test mode xattr data is never written." -  why is that ?

2. for the mobile version, I basically want: episodes for all the shows I selected and any new show.
After I copy to the main storage, I check if the series folder exists on the media and if it does I copy the episode there as well. For brand new shows, such folder does not exists, so I need to created it before I copy to the main storage so that it will be copied later as well....

Sounds more complicated than it is.

**Comment by rednoah** [comment]
I see no reason for doing things in such an intricate way.

The command above will mirror all files. You can limit that with the `--filter` option (i.e. shows that you select). You can also call the same command via the `--def exec` option on given files (i.e. episodes for new shows).

[x] Mirror all files
[x] Mirror only specific files that match arbitrary rules
[x] Mirror specific files passed in via arguments

**Comment by MoonshineSG** [comment]
the only problem is that by the time I run the script is too late... 

Anyways... Thanks for giving this thought. Since I solved my problem, I can close this. Wasn't really a software issue, just a "users has no clue how to do things, but eventually figured it out" thing... :D  

Great work, btw... 👍

**Comment by rednoah** [comment]
Your solution is pretty bad and only incidentally kinda works. I guess you somehow can't process files from `/primary/storage` to `/secondary/mirror` for some reason.

For future reference, using `--db xattr` is the solution for any kind of mirror task:
```
filebot -rename -r /primary/storage --action copy --db xattr --output /secondary/mirror --format {plex}
```

**Comment by MoonshineSG** [comment]
my problem is not copying between the 2 locations - thats easy - , but deciding if to copy or not. 

Not sure why do you say "incidentally kinda works" , but it does work.

**Comment by rednoah** [comment]
1.
Mirror specific shows:
```
filebot -rename -r /primary/storage --action copy --db xattr --output /secondary/mirror --format {plex} --filter "n =~ /Game of Thrones|Big Bang Theory|Silicon Valley/"
```

2.
Mirror new episodes via `--def exec` option from the amc script:
```
--def exec="filebot -rename -r \"{folder}\" --action copy --db xattr --output /secondary/mirror --format {plex}"
```

This is all you need. At no point do you need to decide anything. ;)

**Comment by MoonshineSG** [comment]
I can tell there is much unexplored power in filebot....
