### ISSUE TITLE
amc.groovy creates zero size files

### ISSUE THREAD

**Issue by Just8Will** [filebot/scripts#47]
Hi, 
First off thank you for your work on this project. it's a fantastic piece of software.
I'm using the amc.groovy script to automate some filebot jobs but I have noticed that when it can't find some files to download (e.g. fanart) it'll create a size zero file in the destination location anyway. For example I'll end up with a size zero file "fanart.jpg" or something else in the folder with the tvshow or movie. This wouldn't be an issue except that plex still reads these files as ones it should be using and so I end up with blank artwork in my plex library. It would be better to let plex have a go at finding something if filebot can't get the right files.
I think the simplest way to do this would be to do a quick check on the metadata files as they are created and delete any with size = 0 bytes. This would allow plex to have a go at finding things only if filebot fails to find the correct files.
Is this kind of quick pass over the files created by the script feasible?
Many Thanks.

**Comment by rednoah** [comment]
This issue has been fixed with `4.7.14`.

Here's a more detailed thread on the issue: https://www.filebot.net/forums/viewtopic.php?f=6&t=5329
