### ISSUE TITLE
AMC weird movie grouping issue.

### ISSUE THREAD

**Issue by KurtzPT** [filebot/scripts#52]
I've been having problems with AMC while renaming movies, it groups dozens of movies in the same group which results in all these movies being renamed as the same wrong movie.

**Command used:**
`filebot -script fn:amc --output "D:\output" --action move --conflict auto -no-xattr -non-strict "G:\movies" --log-file "D:\amc.log" --def movieFormat="G:\movies-sorted\{ny}\{fn}" skipExtract=y minFileSize=0 minLengthMS=0 "ut_label=Movies"`

**Log:**
> Run script [fn:amc] at [Wed Oct 24 11:12:06 BST 2018]
Parameter: movieFormat = G:\movies-sorted\{ny}\{fn}
Parameter: skipExtract = y
Parameter: minFileSize = 0
Parameter: minLengthMS = 0
Parameter: ut_label = Movies
Argument[0]: G:\movies
Input: G:\movies\3.An.Eye.For.an.Eye.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\420.Massacre.2018.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTG.mkv
Input: G:\movies\[16+] Garbage (2018) 1080p WEBHD DD 5.1 ESub - DTOne.mkv
Input: G:\movies\A.Man.Called.Jon.2015.1080p.AMZN.WEB-DL.AAC2.0.H.264-NTb.mkv
Input: G:\movies\An Elephants Journey.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\Another.Time.2018.1080p.WEB-DL.DD5.1.H264-CMRG.mkv
Input: G:\movies\Beyond.Words.2017.1080p.AMZN.WEB-DL.DD+5.1.H.264-Cinefeel.mkv
Input: G:\movies\Blossoms.of.Faith.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
Input: G:\movies\Born.Racer.2018.1080p.AMZN.WEB-DL.DD+5.1.H.264-AJP69.mkv
Input: G:\movies\City.of.Joy.2018.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv
Input: G:\movies\Cocaine.Godmother.2017.1080p.AMZN.WEB-DL.DDP2.0.x264-ABM.mkv
Input: G:\movies\Constantine.City.of.Demons.The.Movie.2018.1080p.BluRay.DTS.X264-CMRG.mkv
Input: G:\movies\Constantine.City.of.Demons.The.Movie.2018.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.mkv
Input: G:\movies\Dark House.2017.WEBRip.RR.mkv
Input: G:\movies\Dead.Squad.Temple.of.the.Undead.2018.1080p.AMZN-CBR.WEB-DL.AAC2.0.H.264-NTG.mkv
Input: G:\movies\Desiree.2015.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\Dont.Leave.Home.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\Free.Birds.2014.1080p.BluRay-Remux-HiMMEL.mkv
Input: G:\movies\Gaagua.2017.1080p.WEB-DL.AAC2.0.x264-CMYK.mkv
Input: G:\movies\Garo.and.the.Wailing.Dragon.2012.1080p.BluRay.Remux.AVC.DTS-HD.MA.5.1-ALien.mkv
Input: G:\movies\Ghost Source Zero.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\GOGOL_STRASHNAJA_MEST_2018_WEB_DL_1080p-BLUEBIRD.mkv
Input: G:\movies\Goose Bumps The Movie 2 2014 1080p AMZN WEB-DL DDP2.0 x264-ARiN.mkv
Input: G:\movies\Het.Tweede.Gelaat.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1.mkv
Input: G:\movies\High.Resolution.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\House.by.the.Lake.2017.1080p.KNPY.WEB-DL.AAC2.0.H264-AKME.mkv
Input: G:\movies\How.to.Train.Your.Husband.2018.1080p.AMZN.WEB-DL.DDP2.0.x264-ABM.mkv
Input: G:\movies\Howard.Lovecraft.and.the.Undersea.Kingdom.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\Independents_War_Of_The_Worlds_t00.mkv
Input: G:\movies\Jack.White.Kneeling.At.The.Anthem.D.C.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\K.O.2017.FRENCH.1080p.WEB-DL.DD5.1.H264-PREUMS.mkv
Input: G:\movies\La.Mort.Dans.L.Ame.2017.FRENCH.180p.WEB.H264-PREUMS.mkv
Input: G:\movies\Land.of.Freedom.1970.1080p.AMZN.WEB-DL.DD+2.0.H.264-QOQ.mkv
Input: G:\movies\McDick.2017.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTG.mkv
Input: G:\movies\Rabbit.School.Guardians.of.the.Golden.Egg.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\Raid.Dingue.2016.1080p.BluRay.REMUX.AVC.DTS-HD.MA-HR.mkv
Input: G:\movies\S.M.A.R.T.Chase.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1.mkv
Input: G:\movies\Saa.laenge.jeg.lever.2018.NORDiC.1080p.WEB-DL.H.264-RAPiDCOWS.mkv
Input: G:\movies\Sabina.K.2017.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
Input: G:\movies\Sea.Monsters.2018.1080p.WEB-DL.AAC2.0.H264-FGT.mkv
Input: G:\movies\Seven.in.Heaven.2018.1080p.NF.WEB-DL.DD+5.1.x264-AJP69.mkv
Input: G:\movies\Severance.1988.1080p.Amazon.WEB-DL.DD+2.0.H.264-QOQ.mkv
Input: G:\movies\Sleep.No.More.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\Sorry.For.Your.Loss.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\Strange.Nature.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\Teen.Titans.Go.To.the.Movies.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\Terrortory.2.2018.1080p.AMZN-CBR.WEB-DL.AAC2.0.H.264-NTG.mkv
Input: G:\movies\Th'dread Rattlin'.2018.WEB-DL.RR.mkv
Input: G:\movies\The Legend of Hallowaiian.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\The.God.Plant.2018.1080p.AMZN-CBR.WEB-DL.AAC2.0.H.264-NTG.mkv
Input: G:\movies\The.Hidden.Soldier.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\The.Outer.Wild.2018.1080p.WEB-DL.DD5.1.H264-CMRG.mkv
Input: G:\movies\The.Punished.2018.1080p.WEB-DL.H264.AC3-EVO.mkv
Input: G:\movies\The.Witch.Files.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv
Input: G:\movies\Valentine.DayZ.2018.1080p.AMZN.WEB-DL.DDP2.0.H264-SiGMA.mkv
Input: G:\movies\We.Are.The.Others.2017.FRENCH.1080p.WEB.H264-PREUMS.mkv
Group: [mov:3 2018] => [3.An.Eye.For.an.Eye.2018.1080p.WEB-DL.H264.AC3-EVO.mkv]
Group: [mov:teste de elenco 2011] => [420.Massacre.2018.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTG.mkv, [16+] Garbage (2018) 1080p WEBHD DD 5.1 ESub - DTOne.mkv, Desiree.2015.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv, Dont.Leave.Home.2018.1080p.WEB-DL.H264.AC3-EVO.mkv, Gaagua.2017.1080p.WEB-DL.AAC2.0.x264-CMYK.mkv, Garo.and.the.Wailing.Dragon.2012.1080p.BluRay.Remux.AVC.DTS-HD.MA.5.1-ALien.mkv, Ghost Source Zero.2018.1080p.WEB-DL.H264.AC3-EVO.mkv, Goose Bumps The Movie 2 2014 1080p AMZN WEB-DL DDP2.0 x264-ARiN.mkv, Howard.Lovecraft.and.the.Undersea.Kingdom.2018.1080p.WEB-DL.H264.AC3-EVO.mkv, Jack.White.Kneeling.At.The.Anthem.D.C.2018.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mkv, La.Mort.Dans.L.Ame.2017.FRENCH.180p.WEB.H264-PREUMS.mkv, McDick.2017.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTG.mkv, S.M.A.R.T.Chase.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1.mkv, Saa.laenge.jeg.lever.2018.NORDiC.1080p.WEB-DL.H.264-RAPiDCOWS.mkv, Sabina.K.2017.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv, Sea.Monsters.2018.1080p.WEB-DL.AAC2.0.H264-FGT.mkv, Th'dread Rattlin'.2018.WEB-DL.RR.mkv, The.God.Plant.2018.1080p.AMZN-CBR.WEB-DL.AAC2.0.H.264-NTG.mkv, The.Hidden.Soldier.2018.1080p.WEB-DL.H264.AC3-EVO.mkv, We.Are.The.Others.2017.FRENCH.1080p.WEB.H264-PREUMS.mkv]
Group: [mov:a man called jon 2015] => [A.Man.Called.Jon.2015.1080p.AMZN.WEB-DL.AAC2.0.H.264-NTb.mkv]

Logs above, you can see that huge group "[mov:teste de elenco 2011]". This happens with a random number of movies, with random groups names.

![image](https://user-images.githubusercontent.com/14930057/47425044-12be1400-d781-11e8-8cf2-6edf5686440d.png)

**Comment by rednoah** [comment]
Is there some `nfo` file in the same folder? Note that `Group` is just a pre-processing step, and doesn't necessarily lead to mismatches. I wasn't able to reproduce the issue using the file paths from your logs.

**Comment by KurtzPT** [comment]
No nfo files, just the video files.

Well, I tried again after filebot -clear-cache, and now it worked like expected... I'll keep an eye on this is it happens again I'll reopen it.
