### ISSUE TITLE
Can't download subtitles for media over 30 days old

### ISSUE THREAD

**Issue by wheelerlaw** [filebot/scripts#56]
I am trying to download  subtitles for media that is older than 30 days old using the `suball` script, but when I give a value for the maxAgeDays option, it refuses for any value over 30. But if I don't provide a value, it defaults to 30 days. So how do I download subtitles for media that is over 30 days old?

**Comment by rednoah** [comment]
Disabling anti-abuse limits is only supported for advanced users that know what they're doing. Please read the source code for details. ;)

**Comment by wheelerlaw** [comment]
Oh awesome, thank you.
