### ISSUE TITLE
Select Database for Movie Metadata

### ISSUE THREAD

**Issue by wheelerlaw** [filebot/scripts#57]
I'm located in the US and FileBot keeps trying to name _Harry Potter and the Sorcerer's Stone_ as _Harry Potter and the Philosopher's Stone_. The former of which is the title in the US and the latter is the title in the UK. Additionally, the release year is also incorrect a number of times because many films were released in the US before they were release elsewhere, so the year is different. For instance, _A Place Beyond The Pines_ was released in the US in 2012 (according to IMDB), but TMBD reports it as 2013, since that was the year it was released elsewhere. 

It would be nice if we could pick the database being used for the `amc` script, so that people in the US get the correct title and year. 

Looks like someone has already attempted to do this in #50.

**Comment by rednoah** [comment]
You can pass in `--def movieDB` for a custom data source, but that's not the issue. You'll want to use `TheMovieDB`, and that's default already. You'll want to be able to pass in `--lang en_US` instead of just `--lang en` which seems to default to British English. No idea if that works or not though.

I'll look into the examples you posted and see what can be done about it.

**Comment by rednoah** [comment]
Looks like `Harry Potter and the Philosopher's Stone (2001)` is the official primary title for `en-US`:
https://www.themoviedb.org/movie/671-harry-potter-and-the-philosopher-s-stone?language=en-US


If you are really keen on `Harry Potter and the Sorcerer's Stone` though, then you can specifically select that from the alternative titles in your custom format like so:
```
{movie.alternativeTitles.US}
```

**Comment by rednoah** [comment]
Assuming that the question is really *"How do I get names / years to match what's on IMDb?"* then the `{omdb}` binding is your friend:
```
{omdb.name} ({omdb.released.year}) [{omdb.rating}]
```

Using `TheMovieDB` as primary database generally recommended regardless though, because it's heavily tested and FileBot has many client-side optimizations specifically for `TheMovieDB` in the context of the amc script.

**Comment by wheelerlaw** [comment]
> Looks like _Harry Potter and the Philosopher's Stone (2001)_ is the official primary title for `en-US`

That is most certainly not the case. I take it you don't live in the US, and for that your mistake is excusable. 

From [Wikipedia](https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher's_Stone):
>The book was first published in the United Kingdom on 26 June 1997 by Bloomsbury. **It was published in the United States the following year by Scholastic Corporation under the title _Harry Potter and the Sorcerer's Stone_**. [...] It has been translated into at least 73 other languages, **and has been made into a feature-length film of the same name**, as have all six of its sequels. 

>Scholastic Corporation bought the U.S. rights at the Bologna Book Fair in April 1997 for US$105,000, an unusually high sum for a children's book.[15] Scholastic's Arthur Levine thought that "philosopher" sounded too archaic for readers[32] and after some discussion (including the proposed title "Harry Potter and the School of Magic"[33]), **the American edition was published in September 1998[34] under the title Rowling suggested, _Harry Potter and the Sorcerer's Stone_**.[15] 

(Additionally, iMDB displays the correct US title when viewed in the US and the correct UK title when viewed in the UK (or when you have the settings manually configured as a registered user)).

The fact that The Movie DB does not show the correct US title when passed `--lang en_US` seems to be an issue on their end, and I'll see if I can get in touch with their support staff to rectify this.
