### ISSUE TITLE
`keywords` property missing from `MovieInfo` object

### ISSUE THREAD

**Issue by courtarro** [filebot/scripts#59]
The latest version of `artwork.tmdb.groovy` fails with the following error:

> MissingPropertyException: No such property: keywords for class: net.filebot.web.MovieInfo

According to the [source documentation](https://www.filebot.net/docs/api/net/filebot/web/MovieInfo.html), there is indeed no such property. On my instance, I zapped the three lines related to keyword gathering in the script and it works fine now. Did this property exist before and get removed?

**Comment by rednoah** [comment]
That would be a newly added property. Please upgrade to the latest revision `FileBot r6950` to ensure compatibility with the latest script revisions.
