### ISSUE TITLE
The Movie DB for series?

### ISSUE THREAD

**Issue by courtarro** [filebot/scripts#65]
Filebot supports using TMDB for series. I'm trying to tag [the Millennium series](https://www.themoviedb.org/tv/80855-millenium?language=en-US), which is in this weird place between a movie and a TV show. TheTVDB refuses to keep an entry for it, so I need to use TMDB instead. But the Groovy script for tagging with TMDB is focused on movies only.

Is there a straightforward way to support using TMDB for series in the Groovy scripts?

**Comment by rednoah** [comment]
Please use the FileBot Forums or Discord for end-user support:
* https://www.filebot.net/forums/viewtopic.php?t=1868
* https://www.filebot.net/forums/viewtopic.php?t=12306
