### ISSUE TITLE
Invalid usage: The --output folder option is required

### ISSUE THREAD

**Issue by horst789github** [filebot/scripts#66]
Hi,

i've had my filebot running for years now on synology nas... an update to filebot is now causing errors. the "--output" command now seems to be forced. 

but this is a problem, because i have an amc script, which then shifts either to series or to movies. but if output must be included, then i can't make multiple outputs here. 

my script:
```
LOG="/volume1/Download/amc.log"
EXC="/volume1/Download/amc.txt"
SERIEN="/volume1/Serien/{n}/{n} - {s00e00} - {t}"
FILME="/volume1/video/-------##NEU-UNGESEHEN##-------/{file.parentFile.name}/{n} ({y})"
UNSORTIERT="/volume1/Download/{file.parentFile.name}/{file.structurePathTail}" 

/var/packages/filebot/target/filebot.sh -script fn:amc --lang de --log-file $LOG --action move "$1" --def "seriesFormat=$SERIEN" "movieFormat=$FILME" "unsortedFormat=$UNSORTIERT" -non-strict --def unsorted=y "artwork=n" --def clean=y

/var/packages/filebot/target/filebot.sh -script fn:cleaner "$1" --def root=y
```

if i now specify --output "/volume1/series", of course movies will also be pushed in there etc...

**Comment by rednoah** [comment]
`--output` has no effect on the destination file path if your custom format is already absolute.

Keep in mind that not specifying `--output` is the same as specifying `--output "$PWD"`, which can lead to unexpected behaviour if you're not aware in which `$PWD` you're calling `filebot`, so it's best to be explicit about it.

**Comment by horst789github** [comment]
ok thx
