### ISSUE TITLE
cleaner.groovy - Script does not delete .URL files

### ISSUE THREAD

**Issue by florianmulatz** [filebot/scripts#73]
The script does not clean URL files unless they are explicitly defined via --def exts="URL".
I don't know if it makes a difference that the file extension is in upper case, but as I understand it, the script should ignore upper and lower case. 

Anyway - explicitly defined it works.

Thanks a lot

**Comment by rednoah** [comment]
The extension check is not case sensitive:
https://github.com/filebot/scripts/blob/master/cleaner.groovy#L34

We might make changes if it comes up again. `UPPERCASE` extension are extremely rare and unusual as far as I can tell. Where did you encounter `.URL` files?

**Comment by rednoah** [comment]
https://github.com/filebot/scripts/commit/2466473262a830faf00ef9192a352458ea312aac

**Comment by florianmulatz** [comment]
> The extension check is not case sensitive:
> 
> https://github.com/filebot/scripts/blob/a38568b57956fa1aa8d412a87ac0172b8ba5ef13/cleaner.groovy#L34
> 
> We might make changes if it comes up again. `UPPERCASE` extension are extremely rare and unusual as far as I can tell. Where did you encounter `.URL` files?

I encountered those „.URL“ files from extracted files from serienfans.org

cheers
