### ISSUE TITLE
RFE -- argument / parameter

### ISSUE THREAD

**Issue by florianmulatz** [filebot/scripts#74]
Would be cool to have an argument to define if files without any extension should be deleted.

Cheers

**Comment by rednoah** [comment]
Deleting files without extension by default is a very bad idea. On Unix platforms, many very important files have no extension.

You can however write a script for your own purposes:

e.g. find files without extension:
```
filebot -find /input --filter "none {ext}"
```
e.g. remove files without extension:
```
filebot -find /input --filter "none {ext}" -exec rm {f}
```
`rm` is a Unix command, try`del` if you're on Windows.

**Comment by florianmulatz** [comment]
I understand the argument with the Unix system files - however I see the risk as relatively small if you have to specify an input folder.

Anyhow - the given example should do the trick as well. Currently using a powershell command (as on windows).

Cheers Flo
